[package]
name = "chip8_emulator"
version = "0.1.0"
authors = ["vancha"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "crates/chippie-emulator",
    "crates/chippie-gui",
]

