[package]
name = "chippie-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = [ "canvas", "tokio" ] }
iced_aw = { version = "0.13.0", features = [ "menu" ] }
chippie-emulator = { path = "../chippie-emulator" }
rfd = { version = "0.16.0" }
