[package]
name = "chippie-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = [ "canvas", "async-std" ] }
iced_aw = { version = "0.12.2", features = [ "menu" ] }
chippie-emulator = { path = "../chippie-emulator" }
rfd = { version = "0.16.0" }
